### ISSUE TITLE
Improve header positioning on mobile devices

### ISSUE THREAD

**Issue by 1hiking** [1hiking/Hugo-Doodle#2]
Something like from this [video](https://www.youtube.com/watch?v=vQAvjof1oe4) could be nice

**Comment by EliavYair1** [comment]
ill suggest you to use bootstrap grid system is much more convenient and easy to apply.
plus, its responsive for all devices built-in code block.
[https://getbootstrap.com/docs/4.0/layout/grid/](url)

**Comment by 1hiking** [comment]
Thanks for suggesting this but I prefer doing the old way by hand for now. :P

**Comment by 1hiking** [comment]
Fixed on 59e16045bbe4452cabf45c7992996df6e76d229f
